<a href="https://colab.research.google.com/github/GIGAREHAN/Pytorch/blob/main/Tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

2.10.0+cpu
False


#Creating a Tensor

In [4]:
#using empty
torch.empty(2,3)

tensor([[5.5340e-11, 1.1307e+24, 3.2170e+21],
        [1.2944e+22, 4.7465e+27, 2.2231e-10]])

In [5]:
#check type
type(torch.empty(2,3))

torch.Tensor

In [6]:
#using zeros and ones
torch.zeros(2,3), torch.ones(2,3)

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [7]:
#using rand
torch.rand(2,3)

tensor([[0.7011, 0.9610, 0.6859],
        [0.8230, 0.6961, 0.9260]])

In [10]:
#use seed
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [11]:
#using tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
#using arange
torch.arange(0,6,1).reshape(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [23]:
#using linspace
torch.linspace(0,6,10)

tensor([0.0000, 0.6667, 1.3333, 2.0000, 2.6667, 3.3333, 4.0000, 4.6667, 5.3333,
        6.0000])

In [21]:
#using eye
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
#using full
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

#Tensor Shapes

In [24]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
x.shape

torch.Size([2, 3])

In [29]:
torch.empty_like(x)

tensor([[140487561792896, 140487561792896, 140486970710576],
        [140486970471600, 140486969234480, 140486970753904]])

In [38]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [40]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [44]:
torch.randint_like(x, low=0, high=10)

tensor([[7, 2, 1],
        [5, 6, 3]])

#Tensor Data Types

In [31]:
x.dtype

torch.int64

In [33]:
torch.tensor([[1.0,2.0, 3.0],[4.0, 5.0, 6.0]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [34]:
torch.tensor([[1, 2, 3],[4, 5, 6]], dtype=torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [35]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#Scalar operations

In [45]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [46]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [47]:
x - 2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [48]:
x * 3

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [49]:
x / 3

tensor([[0.3333, 0.6667, 1.0000],
        [1.3333, 1.6667, 2.0000]])

In [50]:
(x * 100) // 3

tensor([[ 33,  66, 100],
        [133, 166, 200]])

In [51]:
x ** 2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

#ELement wise operations

In [55]:
a = torch.rand(2,3)
b = torch.rand(2,3)
a,b

(tensor([[0.8067, 0.8379, 0.7694],
         [0.6694, 0.7203, 0.2235]]),
 tensor([[0.9502, 0.4655, 0.9314],
         [0.6533, 0.8914, 0.8988]]))

In [58]:
#add
a+b

tensor([[1.7569, 1.3034, 1.7008],
        [1.3227, 1.6116, 1.1223]])

In [59]:
a-b

tensor([[-0.1435,  0.3723, -0.1620],
        [ 0.0161, -0.1711, -0.6754]])

In [60]:
a * b

tensor([[0.7665, 0.3900, 0.7166],
        [0.4373, 0.6420, 0.2009]])

In [61]:
a/b

tensor([[0.8490, 1.7998, 0.8260],
        [1.0247, 0.8081, 0.2486]])

In [62]:
a ** b

tensor([[0.8154, 0.9209, 0.7833],
        [0.7694, 0.7464, 0.2601]])

#Reduction Operations

In [63]:
torch.sum(x)

tensor(21)

In [64]:
torch.sum(x, dim=0)

tensor([5, 7, 9])

In [65]:
torch.sum(x, dim=1)

tensor([ 6, 15])

In [67]:
torch.mean(x.to(torch.float32))

tensor(3.5000)

In [68]:
torch.median(x)

tensor(3)

In [69]:
torch.max(x)
torch.min(x)

tensor(1)

In [71]:
torch.argmax(x),torch.argmin(x)

(tensor(5), tensor(0))

In [73]:
torch.std(x.to(torch.float32))

tensor(1.8708)

In [77]:
g = torch.rand(3,3)
h = torch.rand(3,3)

In [78]:
g,h

(tensor([[0.9829, 0.1483, 0.5956],
         [0.3634, 0.7842, 0.5017],
         [0.4497, 0.8660, 0.9567]]),
 tensor([[0.1371, 0.0177, 0.5417],
         [0.6575, 0.6141, 0.9619],
         [0.7244, 0.2700, 0.1576]]))

In [79]:
#matrix multiplication
torch.matmul(g,h)

tensor([[0.6638, 0.2693, 0.7689],
        [0.9289, 0.6235, 1.0302],
        [1.3241, 0.7981, 1.2273]])

In [80]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [81]:
torch.dot(vector1, vector2)

tensor(11)

In [82]:
torch.transpose(x, 0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [84]:
torch.det(g)

tensor(0.2697)

#Comparision Operations

In [92]:
i = torch.randint(size=(2,3), low = 0, high = 10)
j = torch.randint(size=(2,3), low = 0, high = 10)

In [93]:
i, j

(tensor([[6, 3, 6],
         [0, 2, 6]]),
 tensor([[8, 2, 2],
         [9, 5, 0]]))

In [94]:
i < j

tensor([[ True, False, False],
        [ True,  True, False]])

In [95]:
i == j

tensor([[False, False, False],
        [False, False, False]])

In [96]:
i != j

tensor([[True, True, True],
        [True, True, True]])

#Special Functions

In [99]:
k = torch.randint(size=(2,3), low = 0, high = 10)

In [100]:
k

tensor([[7, 5, 2],
        [0, 3, 0]])

In [101]:
torch.log(k)

tensor([[1.9459, 1.6094, 0.6931],
        [  -inf, 1.0986,   -inf]])

In [103]:
torch.exp(k)

tensor([[1.0966e+03, 1.4841e+02, 7.3891e+00],
        [1.0000e+00, 2.0086e+01, 1.0000e+00]])

In [104]:
torch.sqrt(k)

tensor([[2.6458, 2.2361, 1.4142],
        [0.0000, 1.7321, 0.0000]])

In [105]:
torch.sigmoid(k)

tensor([[0.9991, 0.9933, 0.8808],
        [0.5000, 0.9526, 0.5000]])

In [109]:
torch.softmax(k.to(torch.float32),dim=0)

tensor([[9.9909e-01, 8.8080e-01, 8.8080e-01],
        [9.1105e-04, 1.1920e-01, 1.1920e-01]])

In [110]:
torch.relu(k)

tensor([[7, 5, 2],
        [0, 3, 0]])

#Reshaping tensors

In [111]:
a = torch.ones(4,4)

In [112]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [113]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [114]:
b = torch.rand(2,3,4)

In [115]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [125]:
c = torch.rand(226,226,3)
c.unsqueeze(0).shape, c.unsqueeze(1).shape

(torch.Size([1, 226, 226, 3]), torch.Size([226, 1, 226, 3]))

In [128]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])